### ISSUE TITLE
Import info from Motores.xlsx

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-hardware-manual#26]
Import info from [Motores.xlsx](https://github.com/roboticslab-uc3m/teo-hardware-manual/files/1568550/Motores.xlsx).

**Comment by rsantos88** [comment]
@jgvictores do you want a `.md` file with this info in a table using markdown?

**Comment by jgvictores** [comment]
We are in fact considering `.csv`, which can be exported/imported directly using Calc or Excel, and is rendered nicely on GitHub. I still have to put an issue on QA or best-bractices, as it affects several files. :-)

**Comment by rsantos88** [comment]
Ok. I've exported [Motores.xlsx](https://github.com/roboticslab-uc3m/teo-hardware-manual/files/1568550/Motores.xlsx) to a deferents sheets in `.csv`. I can export the table directly with the values or with the functions (without the final results). What do you prefer? This is an example: [protecciones-piernas.csv](https://github.com/rsantos88/teo-hardware-manual/blob/master/protecciones-piernas.csv). The problem is the size of the columns, but you can see how to calculate the values.

**Comment by jgvictores** [comment]
Okay, I had no idea that [Motores.xlsx](https://github.com/roboticslab-uc3m/teo-hardware-manual/files/1568550/Motores.xlsx) contained formulas,, and hadn't contemplated that use case. Let me ask at https://github.com/roboticslab-uc3m/best-practices/issues/20.

**Comment by jgvictores** [comment]
(BTW, thanks a lot! There's lots of info that was hidden in the spreadsheet...)

**Comment by jgvictores** [comment]
TODO: hablarlo con raul

**Comment by jgvictores** [comment]
😂😂😂Vamos, que lo comentaremos en persona! 

:-)

**Comment by jgvictores** [comment]
As commented, the main idea is to keep the `ods` because the file contains formulas.
Then. we'd additionally do raw exports of each page, preserving the origin file name (without the extension) as a prefix.

**Comment by rsantos88** [comment]
done here 29
